config/routes.rb
AguaViva::Application.routes.draw do
  resources :measurements

  resources :cycles

  resources :users

  resources :projects

  resources :wells

  

end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
  belongs_to :well
end

app/controllers/cycles_controller.rb
class CyclesController < ApplicationController
  before_action :set_cycle, only: [:show, :edit, :update, :destroy]

  # GET /cycles
  # GET /cycles.json
  def index
    @cycles = Cycle.all
  end

  # GET /cycles/1
  # GET /cycles/1.json
  def show
  end

  # GET /cycles/new
  def new
    @cycle = Cycle.new
  end

  # GET /cycles/1/edit
  def edit
  end

  # POST /cycles
  # POST /cycles.json
  def create
    @cycle = Cycle.new(cycle_params)

    respond_to do |format|
      if @cycle.save
        format.html { redirect_to @cycle, notice: 'Cycle was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cycle }
      else
        format.html { render action: 'new' }
        format.json { render json: @cycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cycles/1
  # PATCH/PUT /cycles/1.json
  def update
    respond_to do |format|
      if @cycle.update(cycle_params)
        format.html { redirect_to @cycle, notice: 'Cycle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cycles/1
  # DELETE /cycles/1.json
  def destroy
    @cycle.destroy
    respond_to do |format|
      format.html { redirect_to cycles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cycle
      @cycle = Cycle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cycle_params
      params.require(:cycle).permit(:well_id, :start_time, :end_time, :average_pressure, :duration_unsafe)
    end
end

app/helpers/cycles_helper.rb
module CyclesHelper
end

app/views/cycles/_form.html.erb
<%= form_for(@cycle) do |f| %>
  <% if @cycle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cycle.errors.count, "error") %> prohibited this cycle from being saved:</h2>

      <ul>
      <% @cycle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :well_id %><br>
    <%= f.text_field :well_id %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :average_pressure %><br>
    <%= f.text_field :average_pressure %>
  </div>
  <div class="field">
    <%= f.label :duration_unsafe %><br>
    <%= f.text_field :duration_unsafe %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cycles/edit.html.erb
<h1>Editing cycle</h1>

<%= render 'form' %>

<%= link_to 'Show', @cycle %> |
<%= link_to 'Back', cycles_path %>

app/views/cycles/index.html.erb
<h1>Listing cycles</h1>

<table>
  <thead>
    <tr>
      <th>Well</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Average pressure</th>
      <th>Duration unsafe</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cycles.each do |cycle| %>
      <tr>
        <td><%= cycle.well %></td>
        <td><%= cycle.start_time %></td>
        <td><%= cycle.end_time %></td>
        <td><%= cycle.average_pressure %></td>
        <td><%= cycle.duration_unsafe %></td>
        <td><%= link_to 'Show', cycle %></td>
        <td><%= link_to 'Edit', edit_cycle_path(cycle) %></td>
        <td><%= link_to 'Destroy', cycle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cycle', new_cycle_path %>

app/views/cycles/new.html.erb
<h1>New cycle</h1>

<%= render 'form' %>

<%= link_to 'Back', cycles_path %>

app/views/cycles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Well:</strong>
  <%= @cycle.well %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @cycle.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @cycle.end_time %>
</p>

<p>
  <strong>Average pressure:</strong>
  <%= @cycle.average_pressure %>
</p>

<p>
  <strong>Duration unsafe:</strong>
  <%= @cycle.duration_unsafe %>
</p>

<%= link_to 'Edit', edit_cycle_path(@cycle) %> |
<%= link_to 'Back', cycles_path %>